name: Build and Push to docker registry
on: [push]

jobs:
  build_container:
    runs-on: ubuntu-latest
    name: Build the docker container
    steps:
      # To use this repository's private action, you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master
      - name: Get release version
        id: get_version
        run: echo ::set-env name=RELEASE_VERSION::$(echo ${GITHUB_REF:10})
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: florianporada/portfolio
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          buildargs: APP_VERSION=${{ env.RELEASE_VERSION }},RELEASE_DATE=$(date +\"%Y/%m/%d\")
          tags: 'latest,${{ env.RELEASE_VERSION }}'
